dbt_pink_flamingos:
  outputs:
    dev:
      type: postgres
      host: pinkflamingos_postgres
      user: airflow
      pass: airflow
      port: 5432
      dbname: airflow
      schema: public
      threads: 1
  target: dev